### ISSUE TITLE
Should self._tieBreaker be removed?

### ISSUE THREAD

**Issue by cogmission** [numenta/nupic#3245]
It appears this is no longer used?

https://github.com/numenta/nupic/blob/master/src/nupic/research/spatial_pooler.py#L330

It used to exist in the ```inhibitColumns()```  method. Is it ok to just remove it in HTM.Java? ...or was there a substitute put in place?

**Comment by rhyolight** [comment]
It certainly looks like it is not being used anymore. @BoltzmannBrain can you take a look?

**Comment by cogmission** [comment]
Ping?

**Comment by BoltzmannBrain** [comment]
Apologies for the delay. Yes it looks like a vestigial variable. It's also left over w/o purpose in the SP unit tests. We should clean it up.

This also makes me curious if/how ties are handled in the SP. Numpy `argsort` doesn't handle ties gracefully, so [the inhibition here](https://github.com/numenta/nupic/blob/master/src/nupic/research/spatial_pooler.py#L1439) should become

```
randomValues = numpy.random.random(len(overlaps))
winnerIndices = numpy.lexsort((randomValues, overlaps))
```

**Comment by cogmission** [comment]
@BoltzmannBrain 

[The C++ version](https://github.com/numenta/nupic.core/blob/master/src/nupic/algorithms/SpatialPooler.cpp#L1163) (which [calls to here](https://github.com/numenta/nupic.core/blob/master/src/nupic/algorithms/SpatialPooler.cpp#L1147) seems to simply insert the winner into the vector in front of any winners with the same overlap score. So there's no "special" tie breaker logic there either? 

I seem to remember that there was a discussion around taking this out, I just don't remember what was discussed? @scottpurdy @breznak ?

**Comment by rhyolight** [comment]
> I seem to remember that there was a discussion around taking this out, I just don't remember what was discussed? @scottpurdy @breznak ?

https://github.com/numenta/nupic.core/issues/702 is under review. This is something we need to discuss.

**Comment by rhyolight** [comment]
Possible duplicate of https://github.com/numenta/nupic.core/issues/702...

**Comment by subutai** [comment]
We should clean up the unused variable. 

We don't want to randomly break ties - with learning turned off, a given input should lead always to the same result.

numpy.argsort does handle ties gracefully - it does a stable sort (as does the C++ version), which is just as good as the original method of adding a small but constant random offset to the overlap.

**Comment by BoltzmannBrain** [comment]
@subutai relying on numpy.argsort for tie-breaking implies we'll always give preference to higher-indexed columns; if columns 4 and 400 have the same overlap often, column 400 will preferentially win out every time. Using a random tie breaker gets rid of this bias, and can be deterministic with a random seed.

**Comment by subutai** [comment]
> Using a random tie breaker gets rid of this bias, and can be deterministic with a random seed.

Yes, that's how it used to be before. But this has the same net effect as stable sort. The ordering amongst columns is forever fixed with a fixed random tie breaker.

**Comment by cogmission** [comment]
@subutai 
>  The ordering amongst columns is forever fixed with a fixed random tie breaker.

That's a really interesting point! Being "fixed" using an RNG with a seed; and fixed using a static sort both have the net effect of being "fixed".

**Conclusion:**
So then I guess it's fair to say that "done" on this issue simply means to remove the stale tie-breaker code?

**Comment by BoltzmannBrain** [comment]
I still don't agree. Yes these are two sides of the same coin (ensuring determinism), but relying on argsort will always prefer higher-indexed columns. In a 2000 column region, you'll see (slightly) more activity amongst columns 1900-2000 than for 1-100. With a random tie breaker, the "preferred" columns will be dispersed amongst the 2000 columns.

**Comment by vova616** [comment]
how about using connection length as a tie breaker?
same input will results in the same tie breakers, different inputs will create different tie breakers, sounds like a win win to me, it will probably take a bit more memory though.

**Comment by subutai** [comment]
> In a 2000 column region, you'll see (slightly) more activity amongst columns 1900-2000 than for 1-100. With a random tie breaker, the "preferred" columns will be dispersed amongst the 2000 columns.

Yes, but this has zero functional impact as there is no a priori reason to prefer one ordering scheme over another.  In both cases the ordering is fixed and there is a bias towards some cells vs others. The random tie breaker only impacts visualization.

**Comment by subutai** [comment]
> how about using connection length as a tie breaker?

@vova616 If I understand you correctly, this is already the case. The number of active connections into each column is the main sorting criterion. The tie breaker here is only when the number of connections into two columns is the same.

**Comment by cogmission** [comment]
@subutai Wow! @vova616 has a very interesting idea!

If I understand what he's saying correctly, the secondary sort (the tie-breaker) would become the distance between the presynaptic cell and the postsynaptic cell (i.e. the Synapse leading from the closest presynaptic cell would "beat" a further one - in other words, two Segments leading to Cell 27, having the same number of synapses - one leading from Cell 451 and the other leading from cell 1709 would result in (451-27=distance:424 vs. 1709-27=distance:1682) 451 sorted first?

Interesting!
